max_width = 80
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_impl_items = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
