pub(crate) mod generator;
pub(crate) mod scaffoldable;
use crate::utils::get_module_name;

use super::config::Config;
use anyhow::{bail, Result};
use bulloak_syntax::parse;
use generator::generate;

/// Generates aztec-noir code from a `.tree` file. Has a uniform interface with the default
/// solidity backend.
/// TODO: should we define a Backend trait?
pub fn scaffold(text: &str, cfg: &Config) -> Result<String> {
    let forest = parse(text)?;

    match get_module_name(&forest) {
        None => {} // empty tree
        // tree has only one root
        Some(Ok(_)) => {
            // TODO: check if it matches the filename
        }
        Some(Err((expected, second))) => {
            bail!(
                "module name mismatch: expected '{}', found '{}'",
                expected,
                second
            );
        }
    }
    generate(&forest, cfg)
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn single_leaf() {
        let file_contents = r"
Module::Function
└── When thing exists
    └── it should work"
            .trim();
        let output =
            scaffold(&file_contents.to_string(), &Config::default()).unwrap();
        let expected = r"
// Generated by bulloak

#[test]
unconstrained fn test_when_thing_exists() {
    // it should work
}";
        assert_eq!(output.trim(), expected.trim());
    }

    #[test]
    fn two_roots() {
        let file_contents = r"
Module::Function
└── When thing exists
    └── it should work

Module::OtherFunction
└── When thing exists
    └── it should work";
        let output =
            scaffold(&file_contents.to_string(), &Config::default()).unwrap();
        let expected = r"
// Generated by bulloak

#[test]
unconstrained fn test_when_thing_exists() {
    // it should work
}

#[test]
unconstrained fn test_when_thing_exists() {
    // it should work
}";
        assert_eq!(output.trim(), expected.trim());
    }
}
