use crate::test_structure::{Function, Root, SetupHook, TestFunction};

pub(crate) trait Scaffoldable {
    fn scaffold(&self, generate_setup_hooks: bool) -> String;
}

impl Scaffoldable for Root {
    fn scaffold(&self, generate_setup_hooks: bool) -> String {
        let mut output = String::from("// Generated by bulloak\n\n");
        for func in &self.functions {
            match func {
                Function::SetupHook(h) => {
                    if generate_setup_hooks {
                        output.push_str(&h.scaffold(true));
                    }
                }
                Function::TestFunction(f) => {
                    output.push_str(&f.scaffold(generate_setup_hooks));
                    output.push_str("\n");
                }
            }
        }
        output
    }
}

impl Scaffoldable for TestFunction {
    fn scaffold(&self, generate_setup_hooks: bool) -> String {
        let mut output = String::from("");
        output.push_str(if self.expect_fail {
            "#[test(should_fail)]\n"
        } else {
            "#[test]\n"
        });
        output.push_str(&format!("unconstrained fn {}() {{\n", self.name));
        if generate_setup_hooks {
            for hook in &self.setup_hooks {
                output.push_str(&format!("    {}();\n", hook.name));
            }
        }
        for action in &self.actions {
            output.push_str(&format!("    // {}\n", action));
        }
        output.push_str("}\n");
        output
    }
}
impl Scaffoldable for SetupHook {
    fn scaffold(&self, generate_setup_hooks: bool) -> String {
        assert!(generate_setup_hooks);
        format!(
            "/// Setup hook for condition\n\
         unconstrained fn {}() {{\n\
         }}\n\n",
            self.name
        )
    }
}
