use crate::test_structure::{Function, Module, Root, SetupHook, TestFunction};

pub(crate) trait Scaffoldable {
    fn scaffold(&self, generate_setup_hooks: bool) -> String;
}

impl Scaffoldable for Root {
    fn scaffold(&self, generate_setup_hooks: bool) -> String {
        let mut output = String::from("// Generated by bulloak\n\n");

        for func in &self.functions {
            output.push_str(&func.scaffold(generate_setup_hooks));
        }
        for module in &self.modules {
            output.push_str(&module.scaffold(generate_setup_hooks));
        }
        output
    }
}

impl Scaffoldable for TestFunction {
    fn scaffold(&self, generate_setup_hooks: bool) -> String {
        let mut output = String::from("");
        output.push_str(if self.expect_fail {
            "#[test(should_fail)]\n"
        } else {
            "#[test]\n"
        });
        output.push_str(&format!("unconstrained fn {}() {{\n", self.name));
        if generate_setup_hooks {
            for hook in &self.setup_hooks {
                output.push_str(&format!("    {}();\n", hook.name));
            }
        }
        for action in &self.actions {
            output.push_str(&format!("    // {}\n", action));
        }
        output.push_str("}\n\n");
        output
    }
}

impl Scaffoldable for SetupHook {
    fn scaffold(&self, generate_setup_hooks: bool) -> String {
        if generate_setup_hooks {
            format!(
                "/// Setup hook for condition\n\
                unconstrained fn {}() {{\n\
                }}\n\n",
                self.name
            )
        } else {
            format!("")
        }
    }
}

// TODO: can I achieve polymorphism (and skip this trait) without Box<>?
impl Scaffoldable for Function {
    fn scaffold(&self, generate_setup_hooks: bool) -> String {
        match self {
            Function::SetupHook(h) => h.scaffold(generate_setup_hooks),
            Function::TestFunction(f) => f.scaffold(generate_setup_hooks),
        }
    }
}

impl Scaffoldable for Module {
    fn scaffold(&self, generate_setup_hooks: bool) -> String {
        let mut output = format!("\nmod {} {{\n", self.name);

        // indent the definitions inside the module
        for func in &self.functions {
            for line in func.scaffold(generate_setup_hooks).lines() {
                if line.trim().is_empty() {
                    output.push_str("\n");
                    continue;
                }
                output.push_str("    ");
                output.push_str(line);
                output.push_str("\n");
            }
        }

        output.push_str("}\n");
        output
    }
}
