name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "**[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (must match vMAJOR.MINOR.PATCH)"
        required: true
  release:
    types: [created]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          ref:
            ${{ github.event_name == 'workflow_dispatch' &&
            format('refs/tags/{0}', github.event.inputs.tag) || github.ref }}
  upload-assets:
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build & upload ${{ matrix.target }}
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bin: bulloak
          target: ${{ matrix.target }}
          # archives as .tar.gz on UNIX and .zip on Windows by default
          ref:
            ${{ github.event_name == 'workflow_dispatch' &&
            format('refs/tags/{0}', github.event.inputs.tag) || github.ref }}
